version: "3.8"

services:
  app:
    container_name: sukima
    image: sukima:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - conf.env
    ports:
      - mode: ingress
        target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: ./
        target: /sukima
        bind:
          create_host_path: true
      - type: bind
        source: ./storage/hf-cache
        target: /root/.cache/huggingface
        bind:
          create_host_path: true
    command: "bash -c \"alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000\""
    depends_on:
      - database
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
              device_ids: [ "1" ]

  database:
    container_name: postgres
    image: postgres:14-bullseye
    restart: unless-stopped
    env_file:
      - conf.env
    ports:
      - mode: ingress
        target: 5432
        published: 5432
        protocol: tcp
    volumes:
      - type: bind
        source: ./storage/postgres
        target: /var/lib/postgresql/data/
        bind:
          create_host_path: true
